spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user  # Usuario para transacciones
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
