version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  slack: circleci/slack@4.4.4
  docker: circleci/docker@2.2.0

workflows:
  maven:
    jobs:
      - maven/test:
          executor: 
            name: maven/default
            tag: '17.0'
          maven_command: mvn
          command: clean install
          verify_dependencies: false