version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - run:
          name: Install Maven
          command: apt-get update && apt-get install -y maven
      - run:
          name: Run mvn clean install
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}