version: 2.1

jobs:
  build:
    docker:
      - image: cimg/maven:3.8.7-jdk-17  # Imagen con Maven y JDK 17 preinstalados
    steps:
      - checkout  # Descargar el código fuente del repositorio
      - run:
          name: Run mvn clean install
          command: mvn clean install