# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.11
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  build-and-test:
    jobs:
      - build-and-test
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
      