# Usa la última versión del motor de pipeline de CircleCI
version: 2.1

# Define el job que se invocará en el workflow
jobs:
  build:
    # Especifica el entorno de ejecución, en este caso, una imagen con Maven y Java preinstalados
    docker:
      # Usa una imagen de Maven con JDK 17.0.8
      - image: cimg/openjdk:17-jdk

    # Define los pasos del job
    steps:
      # Paso 1: Check out del código
      - checkout

      # Paso 2: Cachear dependencias Maven para acelerar las futuras ejecuciones
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Paso 3: Ejecutar Maven para compilar el proyecto
      - run:
          name: "Compilar proyecto con Maven"
          command: "mvn clean install"

      # Paso 4: Guardar dependencias en caché para futuros builds
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Paso 5: Guardar los artefactos de compilación si lo deseas (opcional)
      - store_artifacts:
          path: target
          destination: maven-artifacts

# Define el workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
